# Generated by Django 4.2.1 on 2023-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_page_delete_aboutpage_delete_contactspage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Главная'), ('about', 'О нас'), ('requisites', 'Реквизиты'), ('faq', 'FAQ'), ('contacts', 'Contacts')], default='home', max_length=20),
        ),
    ]
