# Generated by Django 4.2.1 on 2023-09-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('home', 'Главная'), ('about', 'О нас'), ('requisites', 'Реквизиты'), ('faq', 'FAQ'), ('contacts', 'Contacts'), ('privacy-policy', 'Privacy-policy'), ('coupons', 'Coupons')], default='home', max_length=20),
        ),
    ]
